spring:
  application:
    name: openjobs

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:openjobs}
    username: ${POSTGRES_USER:openjobs}
    password: ${POSTGRES_PASSWORD:openjobs_dev_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  jwt:
    expiration: ${JWT_EXPIRATION:9000000}
    key: ${JWT_KEY:dr+C8Nu229pp7XKksvY1mpGU7Ysk1/9h/nv3Ul7+iCvbv9Jw77oQwcQ56ItUsyz2NHwmcmDZq1UVMUXE65VAhm7OIaJv/xNQ37gKM+QlSEmkGlC4ohFD+/niVvFpy1rrjO7tkSzGIRL+lQM2UZUV4MFU+s0CHwRRkfGwR2Na8Oxc9X9olcw2Fh/4Pvgvea3CAvsZnTSVbpLwNDvDucwAPBRi2nGOa0RvLXAQM5xMFopcGVU4HJQyQXidxMZLsrSrdZPs6JazdhUC0y++5byZAeZbEK+TKpdbthIx0U9VNDq/}