# Replace only the simple upstream/import inside the existing API site.
# Remove the local listener generated by previous deploy.sh versions.
function brace_delta(line, copy, opened, closed) {
    copy = line
    opened = gsub(/\{/, "", copy)
    copy = line
    closed = gsub(/\}/, "", copy)
    return opened - closed
}
{
    trimmed = $0
    sub(/^[ \t]+/, "", trimmed)
    sub(/[ \t\r]+$/, "", trimmed)
    if (trimmed == "# OpenJobs API: managed listener. Preserve this import for future deployments.") {
        skip_pending = 1
        next
    }
    if (skip_pending) {
        if (trimmed == "") next
        if (trimmed != "http://:" legacy_port " {" && trimmed != "http://127.0.0.1:" legacy_port " {") exit 42
        skip_pending = 0
        skip_depth = brace_delta($0)
        next
    }
    if (skip_depth > 0) {
        skip_depth += brace_delta($0)
        next
    }
    if (!in_site && trimmed == host " {") {
        in_site = 1
        site_depth = 0
        sites++
    }
    if (in_site && site_depth == 1) {
        if (trimmed == "reverse_proxy 127.0.0.1:" legacy_port ||
            trimmed == "reverse_proxy 127.0.0.1:" blue_port ||
            trimmed == "reverse_proxy 127.0.0.1:" green_port) {
            match($0, /^[ \t]*/)
            print substr($0, 1, RLENGTH) "import " upstream
            routes++
            next
        }
        if (trimmed == "import " upstream) routes++
    }
    print
    if (in_site) {
        site_depth += brace_delta($0)
        if (site_depth == 0) in_site = 0
    }
}
END {
    if (sites != 1 || routes != 1 || skip_depth || skip_pending || in_site) exit 42
}
