package com.antony.openjobs.modules.permissions.model;

public enum Permission {
    PERMISSION_READ("PERMISSION_READ"),
    PERMISSION_CREATE("PERMISSION_CREATE"),
    PERMISSION_UPDATE("PERMISSION_UPDATE"),
    PERMISSION_DELETE("PERMISSION_DELETE"),
    ROLEPERMISSION_READ("ROLEPERMISSION_READ"),
    ROLEPERMISSION_CREATE("ROLEPERMISSION_CREATE"),
    ROLEPERMISSION_UPDATE("ROLEPERMISSION_UPDATE"),
    ROLEPERMISSION_DELETE("ROLEPERMISSION_DELETE"),
    USER_READ("USER_READ"),
    USER_UPDATE("USER_UPDATE"),
    USER_DELETE("USER_DELETE"),
    ROLE_READ("ROLE_READ"),
    ROLE_CREATE("ROLE_CREATE"),
    ROLE_UPDATE("ROLE_UPDATE"),
    POST_READ("POST_READ"),
    POST_CREATE("POST_CREATE"),
    POST_UPDATE("POST_UPDATE"),
    POST_DELETE("POST_DELETE"),
    LIKE_CREATE("LIKE_CREATE"),
    LIKE_UPDATE("LIKE_UPDATE"),
    LIKE_DELETE("LIKE_DELETE"),
    JOB_READ("JOB_READ"),
    JOB_CREATE("JOB_CREATE"),
    JOB_UPDATE("JOB_UPDATE"),
    JOB_DELETE("JOB_DELETE"),
    APPLICATION_READ("APPLICATION_READ"),
    APPLICATION_CREATE("APPLICATION_CREATE"),
    APPLICATION_DELETE("APPLICATION_DELETE");

    private final String code;

    Permission(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
